# NLP Modeling

How do we quantify a document?

- [Setup](#setup)
- [Data Representation](#data-representation)
    - [Bag of Words](#bag-of-words)
    - [TF-IDF](#tf-idf)
    - [Bag Of Ngrams](#bag-of-ngrams)
- [Modeling](#modeling)
    - [Modeling Results](#modeling-results)
- [Next Steps](#next-steps)

## Setup

In [1]:
from pprint import pprint
import pandas as pd
import nltk
import re

def clean(text: str) -> list:
    'A simple function to cleanup text data'
    wnl = nltk.stem.WordNetLemmatizer()
    stopwords = set(nltk.corpus.stopwords.words('english'))
    text = (text.encode('ascii', 'ignore')
             .decode('utf-8', 'ignore')
             .lower())
    words = re.sub(r'[^\w\s]', '', text).split() # tokenization
    return [wnl.lemmatize(word) for word in words if word not in stopwords]

## Data Representation

Simple data for demonstration.

In [2]:
data = [
    'Python is pretty cool',
    'Python is a nice programming language with nice syntax',
    'I think SQL is cool too',
]

### Bag of Words

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
bag_of_words = cv.fit_transform(data)

In [4]:
bag_of_words.todense()

matrix([[1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
        [0, 1, 1, 2, 0, 1, 1, 0, 1, 0, 0, 1],
        [1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0]])

In [5]:
cv.get_feature_names()

['cool',
 'is',
 'language',
 'nice',
 'pretty',
 'programming',
 'python',
 'sql',
 'syntax',
 'think',
 'too',
 'with']

Here `bag_of_words` is a **sparse matrix**. Usually you should keep it as such,
but for demonstration we'll view the data within.

In [6]:
pprint(data)
pd.DataFrame(bag_of_words.todense(), columns=cv.get_feature_names())

['Python is pretty cool',
 'Python is a nice programming language with nice syntax',
 'I think SQL is cool too']

,cool,is,language,nice,pretty,programming,python,sql,syntax,think,too,with
0,1,1,0,0,1,0,1,0,0,0,0,0
1,0,1,1,2,0,1,1,0,1,0,0,1
2,1,1,0,0,0,0,0,1,0,1,1,0

### TF-IDF

- a measure that helps identify how important a word is in a document
- combination of how often a word appears in a document (**tf**) and how unqiue the word
  is among documents (**idf**)
- used by search engines
- naturally helps filter out stopwords
- tf is for a single document, idf is for a corpus

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
bag_of_words = tfidf.fit_transform(data)

pprint(data)
pd.DataFrame(bag_of_words.todense(), columns=tfidf.get_feature_names())

['Python is pretty cool',
 'Python is a nice programming language with nice syntax',
 'I think SQL is cool too']

,cool,is,language,nice,pretty,programming,python,sql,syntax,think,too,with
0,0.480458,0.373119,0.000000,0.000000,0.631745,0.000000,0.480458,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.197673,0.334689,0.669378,0.000000,0.334689,0.254540,0.000000,0.334689,0.000000,0.000000,0.334689
2,0.383770,0.298032,0.000000,0.000000,0.000000,0.000000,0.000000,0.504611,0.000000,0.504611,0.504611,0.000000

In [8]:
tfidf.idf_

array([1.28768207, 1.        , 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.28768207, 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.69314718])

In [9]:
tfidf.get_feature_names()

['cool',
 'is',
 'language',
 'nice',
 'pretty',
 'programming',
 'python',
 'sql',
 'syntax',
 'think',
 'too',
 'with']

In [10]:
pd.Series(dict(zip(tfidf.get_feature_names(), tfidf.idf_))).sort_values()

is             1.000000
cool           1.287682
python         1.287682
language       1.693147
nice           1.693147
pretty         1.693147
programming    1.693147
sql            1.693147
syntax         1.693147
think          1.693147
too            1.693147
with           1.693147
dtype: float64

### Bag Of Ngrams

For either `CountVectorizer` or `TfidfVectorizer`, you can set the `ngram_range`
parameter.

In [11]:
cv = CountVectorizer(ngram_range=(2, 2))
bag_of_words = cv.fit_transform(data)

In [12]:
pprint(data)
pd.DataFrame(bag_of_words.todense(), columns=cv.get_feature_names())

['Python is pretty cool',
 'Python is a nice programming language with nice syntax',
 'I think SQL is cool too']

,cool too,is cool,is nice,is pretty,language with,nice programming,nice syntax,pretty cool,programming language,python is,sql is,think sql,with nice
0,0,0,0,1,0,0,0,1,0,1,0,0,0
1,0,0,1,0,1,1,1,0,1,1,0,0,1
2,1,1,0,0,0,0,0,0,0,0,1,1,0

## Modeling

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

df = pd.read_csv('spam_clean.csv')

In [14]:
df.head()

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [15]:
cv = CountVectorizer()
X = cv.fit_transform(df.text.apply(clean).apply(' '.join))
y = df.label

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=12)

In [17]:
pd.DataFrame(X_train[:5, :].todense(), columns=cv.get_feature_names())

,008704050406,0089my,0121,01223585236,01223585334,0125698789,02,020603,0207,02070836089,...,zebra,zed,zero,zhong,zindgi,zoe,zogtorius,zoom,zouk,zyada
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
tree = DecisionTreeClassifier(max_depth=5)
tree.fit(X_train, y_train)

tree.score(X_train, y_train)

0.9306708548350908

In [19]:
tree.predict(X_train)

array(['ham', 'ham', 'ham', ..., 'ham', 'ham', 'ham'], dtype=object)

In [20]:
tree.score(X_test, y_test)

0.915695067264574

### Modeling Results

A super-useful feature of decision trees and linear models is that they do some
built-in feature selection through the coefficeints or feature importances:

In [21]:
cv.get_feature_names()

['008704050406',
 '0089my',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '020603',
 '0207',
 '02070836089',
 '02072069400',
 '02073162414',
 '02085076972',
 '020903',
 '021',
 '050703',
 '0578',
 '06',
 '060505',
 '061104',
 '07008009200',
 '07046744435',
 '07090201529',
 '07090298926',
 '07099833605',
 '071104',
 '07123456789',
 '0721072',
 '07732584351',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07786200117',
 '077xxx',
 '078',
 '07801543489',
 '07808',
 '07808247860',
 '07808726822',
 '07815296484',
 '07821230901',
 '0784987',
 '0789xxxxxxx',
 '0794674629107880867867',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08450542832',
 '08452810071',
 '08452810073',
 '08452810075over18s',
 '0870',
 '08700621170150p',
 '08701213186',
 '08701237397',
 '08701417012',
 '08701417012150p',
 '0870141701216',
 '087016248',
 '08701752560',
 '087018728737',
 '0870241182716',
 '08702490080',
 '08702840625',
 '08702840625comuk',
 '08704439680',
 '08704439680tscs',
 '08706091795',
 '0870737910216yrs',
 '08707500020',
 '08707509020',
 '0870753331018',
 '08707808226',
 '08708034412',
 '08708800282',
 '08709222922',
 '08709501522',
 '0870k',
 '087104711148',
 '08712101358',
 '08712103738',
 '0871212025016',
 '08712300220',
 '087123002209am7pm',
 '08712317606',
 '08712400200',
 '08712400603',
 '08712402050',
 '08712402578',
 '08712402779',
 '08712402902',
 '08712402972',
 '08712404000',
 '08712405020',
 '08712405022',
 '08712460324',
 '08712460324nat',
 '08712466669',
 '0871277810710pmin',
 '0871277810810',
 '0871277810910pmin',
 '087143423992stop',
 '087147123779am7pm',
 '08714712379',
 '08714712388',
 '08714712394',
 '08714712412',
 '08714714011',
 '08714719523',
 '08715203028',
 '08715203649',
 '08715203652',
 '08715203656',
 '08715203677',
 '08715203685',
 '08715203694',
 '08715205273',
 '08715500022',
 '08715705022',
 '08717111821',
 '08717168528',
 '08717205546',
 '08717507382',
 '08717507711',
 '08717509990',
 '08717890890150',
 '08717895698',
 '08717898035',
 '08718711108',
 '08718720201',
 '08718723815',
 '08718725756',
 '08718726270',
 '08718726270150gbpmtmsg18',
 '08718726970',
 '08718726971',
 '08718726978',
 '087187272008',
 '08718727868',
 '08718727870',
 '08718729755',
 '08718729758',
 '08718730555',
 '08718730666',
 '08718738001',
 '08718738002',
 '08718738034',
 '08719180219',
 '08719180248',
 '08719181259',
 '08719181503',
 '08719181513',
 '08719839835',
 '08719899217',
 '08719899229',
 '08719899230',
 '09041940223',
 '09050000301',
 '09050000332',
 '09050000460',
 '09050000555',
 '09050000878',
 '09050000928',
 '09050001295',
 '09050001808',
 '09050002311',
 '09050003091',
 '09050005321',
 '09050090044',
 '09050280520',
 '09053750005',
 '09056242159',
 '09057039994',
 '09058091854',
 '09058091870',
 '09058094454',
 '09058094455',
 '09058094507',
 '09058094565',
 '09058094583',
 '09058094594',
 '09058094597',
 '09058094599',
 '09058095107',
 '09058095201',
 '09058097189',
 '09058097218',
 '09058098002',
 '09058099801',
 '09061104276',
 '09061104283',
 '09061209465',
 '09061213237',
 '09061221061',
 '09061221066',
 '09061701444',
 '09061701461',
 '09061701851',
 '09061701939',
 '09061702893',
 '09061743386',
 '09061743806',
 '09061743810',
 '09061743811',
 '09061744553',
 '09061749602',
 '09061790121',
 '09061790125',
 '09061790126',
 '09063440451',
 '09063442151',
 '09063458130',
 '0906346330',
 '09064011000',
 '09064012103',
 '09064012160',
 '09064015307',
 '09064017295',
 '09064017305',
 '09064018838',
 '09064019014',
 '09064019788',
 '09065069120',
 '09065069154',
 '09065171142stopsms08',
 '09065171142stopsms08718727870150ppm',
 '09065174042',
 '09065394514',
 '09065394973',
 '09065989180',
 '09065989182',
 '09066350750',
 '09066358152',
 '09066358361',
 '09066361921',
 '09066362206',
 '09066362220',
 '09066362231',
 '09066364311',
 '09066364349',
 '09066364589',
 '09066368327',
 '09066368470',
 '09066368753',
 '09066380611',
 '09066382422',
 '09066612661',
 '09066649731from',
 '09066660100',
 '09071512432',
 '09071512433',
 '09071517866',
 '09077818151',
 '09090204448',
 '09090900040',
 '09094100151',
 '09094646631',
 '09094646899',
 '09095350301',
 '09096102316',
 '09099725823',
 '09099726395',
 '09099726429',
 '09099726481',
 '09099726553',
 '09111030116',
 '09111032124',
 '09701213186',
 '0anetworks',
 '10',
 '100',
 '1000',
 '10000',
 '100000',
 '1000call',
 '100603',
 '100psms',
 '1010',
 '1013',
 '101mega',
 '1030',
 '10803',
 '10am',
 '10am7pm',
 '10am9pm',
 '10k',
 '10p',
 '10pmin',
 '10ppm',
 '10th',
 '11',
 '1120',
 '113',
 '1131',
 '11414',
 '1148',
 '116',
 '1172',
 '118pmsg',
 '11mths',
 '12',
 '120',
 '12000pes',
 '1205',
 '121',
 '1225',
 '123',
 '1230',
 '125',
 '1250',
 '125gift',
 '128',
 '12hours',
 '12hrs',
 '12mths',
 '12price',
 '13',
 '130',
 '131004',
 '1327',
 '13404',
 '139',
 '140',
 '1405',
 '140ppm',
 '145',
 '1450',
 '146tf150p',
 '14thmarch',
 '150',
 '1500',
 '150ea',
 '150msg',
 '150p',
 '150pday',
 '150perweeksub',
 '150perwksub',
 '150pm',
 '150pmeg',
 '150pmin',
 '150pmmorefrommobile2bremovedmobypobox734ls27yf',
 '150pmsg',
 '150pmsgrcvd',
 '150pmsgrcvdhgsuite3422landsroww1j6hl',
 '150pmt',
 '150pmtmsg',
 '150pmtmsgrcvd18',
 '150ppermesssubscription',
 '150ppm',
 '150ppmpobox10183bhamb64xe',
 '150ppmsg',
 '150prcvd',
 '150psms',
 '150ptext',
 '150ptone',
 '150pwk',
 '150week',
 '150wk',
 '151',
 '1526',
 '153',
 '15541',
 '15pmin',
 '16',
 '1680',
 '169',
 '16only',
 '177',
 '18',
 '180',
 '181104',
 '1843',
 '186150morefrmmob',
 '18only',
 '18ptxt',
 '18yrs',
 '195',
 '1956669',
 '1appledayno',
 '1childish',
 '1cup',
 '1da',
 '1er',
 '1hanuman',
 '1his',
 '1hr',
 '1im',
 '1lemondayno',
 '1mcflyall',
 '1million',
 '1minmobsmorelkpobox177hp51fl',
 '1month',
 '1pm',
 '1st',
 '1st4terms',
 '1stchoicecouk',
 '1stone',
 '1tulsi',
 '1u',
 '1unbreakable',
 '1winaweek',
 '1winawk',
 '1x150pwk',
 '1yf',
 '20',
 '200',
 '2000',
 '20000',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2025050',
 '20f',
 '20m12aq',
 '20p',
 '20pmin',
 '21',
 '211104',
 '215',
 '21870000hi',
 '21m',
 '21st',
 '22',
 '220cm2',
 '2309',
 '230ish',
 '24',
 '241',
 '241004',
 '247mp',
 '24hrs',
 '24m',
 '24th',
 '25',
 '250',
 '250k',
 '255',
 '25f',
 '25p',
 '260305',
 '261004',
 '261104',
 '2667',
 '26th',
 '2703',
 '27603',
 '28',
 '2814032',
 '285',
 '28days',
 '28th',
 '28thfebtcs',
 '290305',
 '29100',
 '29m',
 '2b',
 '2bajarangabali',
 '2bold',
 '2c',
 '2channel',
 '2day',
 '2daylove',
 '2end',
 '2exit',
 '2ez',
 '2getha',
 '2geva',
 '2go',
 '2godid',
 '2gthr',
 '2hrs',
 '2im',
 '2kbsubject',
 '2marrow',
 '2moro',
 '2morow',
 '2morro',
 '2morrow',
 '2morrowxxxx',
 '2mro',
 '2mrw',
 '2naughty',
 '2nd',
 '2nhite',
 '2nights',
 '2nite',
 '2nitetell',
 '2optout',
 '2optoutd3wv',
 '2p',
 '2police',
 '2px',
 '2rcv',
 '2stop',
 '2stoptx',
 '2stoptxt',
 '2u',
 '2u2',
 '2untamed',
 '2waxsto',
 '2when',
 '2wks',
 '2wt',
 '2wu',
 '2years',
 '2yr',
 '2yrs',
 '30',
 '300',
 '3000',
 '300603',
 '300603tcsbcm4235wc1n3xxcallcost150ppmmobilesvary',
 '300p',
 '3030',
 '30apr',
 '30pptxt',
 '30th',
 '31',
 '3100',
 '310303',
 '311004',
 '31pmsg150p',
 '32000',
 '3230',
 '32323',
 '326',
 '32f',
 '330',
 '3350',
 '3365',
 '350',
 '3510i',
 '35p',
 '3650',
 '36504',
 '3680',
 '3680offer',
 '373',
 '3750',
 '391784',
 '3aj',
 '3cover',
 '3d',
 '3days',
 '3db',
 '3g',
 '3gbp',
 '3hrs',
 '3lions',
 '3lp',
 '3maruti',
 '3miles',
 '3mins',
 '3mobile',
 '3optical',
 '3pound',
 '3qxj9',
 '3rd',
 '3sentiment',
 '3u',
 '3unkempt',
 '3uz',
 '3wife',
 '3wk',
 '3wks',
 '3x150pw',
 '3xx',
 '40',
 '400',
 '400minscall',
 '402',
 '4041',
 '40411',
 '40533',
 '40gb',
 '40mph',
 '415',
 '41685',
 '41782',
 '420',
 '42049',
 '4217',
 '42478',
 '42810',
 '430',
 '434',
 '44',
 '4403ldnw1a7rw18',
 '447797706009',
 '447801259231',
 '447per',
 '448712404000please',
 '449050000301',
 '449071512431',
 '449month',
 '45',
 '450',
 '450p',
 '450pw',
 '45239',
 '46',
 '47',
 '4712',
 '4742',
 '48',
 '4882',
 '48922',
 '49557',
 '4a',
 '4cook',
 '4d',
 '4eva',
 '4few',
 '4fil',
 '4get',
 '4give',
 '4got',
 '4goten',
 '4info',
 '4jx',
 '4lux',
 '4mths',
 '4o',
 '4pavanaputra',
 '4press',
 '4rowdy',
 '4some1',
 '4tctxt',
 '4th',
 '4the',
 '4thnovbehind',
 '4txt120',
 '4txt120p',
 '4u',
 '4ui',
 '4utxt',
 '4w',
 '4ward',
 '4wrd',
 '4years',
 '50',
 '500',
 '5000',
 '500000',
 '50500',
 '505060',
 '50award',
 '50p',
 '515',
 '515pm',
 '5226',
 '526',
 '528',
 '530',
 '532',
 '54',
 '542',
 '545',
 '5903',
 '5digital',
 '5free',
 '5ful',
 '5gardener',
 '5gently',
 '5im',
 '5ish',
 '5k',
 '5min',
 '5mls',
 '5month',
 '5p',
 '5pm',
 '5sankatmochan',
 '5terror',
 '5th',
 '5wb',
 '5we',
 '5wkg',
 '5wq',
 '5years',
 '600',
 '6031',
 '60400thousadi',
 '60p',
 '60pmin',
 '61200',
 '61610',
 '62220cncl',
 '6230',
 '62468',
 '62735450',
 '630',
 '63miles',
 '645',
 '645pm',
 '650',
 '6669',
 '67441233',
 '68866',
 '69101',
 '69200',
 '69669',
 '69696',
 '69698',
 '69855',
 '6986618',
 '69876',
 '69888',
 '69888nyt',
 '69911150p',
 '69969',
 '69988',
 '6cruel',
 '6days',
 '6hl',
 '6housemaid',
 '6hrs',
 '6ish',
 '6missed',
 '6months',
 '6pm',
 '6ramaduth',
 '6romantic',
 '6th',
 '6times',
 '6wu',
 '6zf',
 '700',
 '71',
 '725',
 '7250',
 '7250i',
 '730',
 '730ish',
 '730pm',
 '731',
 '74355',
 '750',
 '75000',
 '7548',
 '7634',
 '7684',
 '7732584351',
 '78',
 '786',
 '7876150ppm',
 '78pmin',
 '79',
 '7am',
 '7cfca1a',
 '7children',
 '7ish',
 '7mahaveer',
 '7oz',
 '7pm',
 '7romantic',
 '7shy',
 '7th',
 '7ws',
 '7zs',
 '80',
 '800',
 '8000930705',
 '80062',
 '8007',
 '80082',
 '80086',
 '80122300pwk',
 '80155',
 '80160',
 '80182',
 '8027',
 '80488',
 '80488biz',
 '80608',
 '8077',
 '80878',
 '81010',
 '81151',
 '81303',
 '81618',
 '816183',
 '82242',
 '82277',
 '82277unsub',
 '82324',
 '82468',
 '830',
 '83021',
 '83039',
 '83049',
 '83110',
 '83118',
 '83222',
 '83332please',
 '83338',
 '83355',
 '83370',
 '83383',
 '83435',
 '83600',
 '83738',
 '84',
 '84025',
 '84122',
 '84128',
 '84128custcare',
 '84199',
 '84484',
 '85',
 '850',
 '85023',
 '85069',
 '85222',
 '85233',
 '8552',
 '85555',
 '86021',
 '861',
 '863',
 '864233',
 '86688',
 '86888',
 '87021',
 '87066',
 '87070',
 '87077',
 '87121',
 '87131',
 '8714714',
 '87239',
 '87575',
 '8800',
 '88039',
 '88039skilgmetscs087147403231winawkage16150perwksub',
 '88066',
 '88088',
 '88222',
 '8830',
 '88600',
 '88800',
 '8883',
 '88877',
 '88877free',
 '88888',
 '89034',
 '89070',
 '89080',
 '89105',
 '89123',
 '89545',
 '89555',
 '89693',
 '89938',
 '8am',
 '8attractive',
 '8ball',
 '8hr',
 '8lb',
 '8lovable',
 '8neighbour',
 '8o',
 '8pm',
 '8th',
 '8wp',
 '900',
 '9061100010',
 '9153',
 '924',
 '930',
 '945',
 '946',
 '95pax',
 '96',
 '97n7qp',
 '98321561',
 '9996',
 '9ae',
 '9am',
 '9am11pm',
 '9decent',
 '9funny',
 '9ja',
 '9pm',
 '9t',
 '9th',
 '9yt',
 '____',
 '_ll',
 '_thanks',
 'a150',
 'a21',
 'a30',
 'aa',
 'aah',
 'aaniye',
 'aaooooright',
 'aathilove',
 'aathiwhere',
 'ab',
 'abbey',
 'abdomen',
 'abeg',
 'abel',
 'aberdeen',
 'abi',
 'ability',
 'abiola',
 'abj',
 'able',
 'abnormally',
 'aboutas',
 'abroad',
 'absence',
 'absolutely',
 'abstract',
 'abt',
 'abta',
 'aburo',
 'abuse',
 'abuser',
 'ac',
 'academic',
 'acc',
 'accent',
 'accenture',
 'accept',
 'access',
 'accessible',
 'accidant',
 'accident',
 'accidentally',
 'accommodation',
 'accommodationvouchers',
 'accomodate',
 'accomodations',
 'accordin',
 'accordingly',
 'accordinglyor',
 'account',
 'accounting',
 'accumulation',
 'achanammarakheshqatar',
 'ache',
 'achieve',
 'acid',
 'acknowledgement',
 'acl03530150pm',
 'acnt',
 'acoentry41',
 'across',
 'acsmsrewards',
 'act',
 'acted',
 'actin',
 'acting',
 'action',
 'activ8',
 'activate',
 'active',
 'activity',
 'actor',
 'actual',
 'actually',
 'acwicmb3cktz8r74',
 'ad',
 'adam',
 'add',
 'addamsfa',
 'added',
 'addicted',
 'addie',
 'adding',
 'address',
 'addressull',
 'adewale',
 'adi',
 ...]

In [22]:
tree.feature_importances_

array([0., 0., 0., ..., 0., 0., 0.])

In [23]:
pd.Series(dict(zip(cv.get_feature_names(), tree.feature_importances_))).sort_values().tail(12)

probably    0.006182
youre       0.010495
stop        0.011767
ill         0.013857
service     0.020439
mobile      0.026495
reply       0.042182
later       0.059484
claim       0.073024
text        0.086027
txt         0.280117
call        0.357470
dtype: float64

## Next Steps

- Try other model types

    [Naive Bayes](https://en.wikipedia.org/wiki/Naive_Bayes_classifier)
    ([`sklearn`
    docs](https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html))
    is a very popular classifier for NLP tasks.

- Look at other metrics, is accuracy the best choice here?

- Try ngrams instead of single words

- Try a combination of ngrams and words (`ngram_range=(1, 2)` for words and
  bigrams)

- Try using tf-idf instead of bag of words

- Combine the top `n` performing words with the other features that you have
  engineered (the `CountVectorizer` and `TfidfVectorizer` have a `vocabulary`
  argument you can use to restrict the words used)

    ```python
    best_words = (
        # or, e.g. lm.coef_
        pd.Series(dict(zip(cv.get_feature_names(), tree.feature_importances_)))
        .sort_values()
        .tail(5)
        .index
    )

    cv = CountVectorizer(vocabulary=best_words)
    X = cv.fit_transform(df.text.apply(clean).apply(' '.join))

    # for demonstration
    pd.DataFrame(X.todense(), columns=cv.get_feature_names())
    ```